fdataPath: D:/dev/istock-data/fdata/
sinaKdataPath: D:/dev/istock-data/kdata/sina
dzhKdataPath: D:/dev/istock-data/kdata/dzh
tushareKdataPath: D:/dev/istock-data/kdata/tushare
tushareFdataPath: D:/dev/istock-data/fdata/tushare
eastmoneyFataPath: D:/dev/istock-data/fdata/eastmoney
kdataPath163: D:/dev/istock-data/kdata/163
reportPath: D:/dev/istock-data/reports
musterPath: d:/dev/istock-data/kdata/muster
tmpMusterPath: d:/dev/istock-data/kdata/muster_tmp
tushareItemsFile: D:/dev/istock-data/tushare_items.json
holdsFile: D:/dev/istock-data/holds.txt
favorsFile: D:/dev/istock-data/favors.txt
favorsPath: D:/dev/istock-data/favors
bluechipsFile: D:/dev/istock-data/bluechips.json
topicsFile: D:/dev/istock-data/topics.txt
fvaluesOfHLFile: D:/dev/istock-data/fvaluesOfHL.txt
dailyMeansFile: D:/dev/istock-data/dailyMeans.txt
sz50File: D:/dev/istock-data/sz50.csv
hs300File: D:/dev/istock-data/hs300.csv
huaFile: d:/dev/istock-data/hua.txt
huaPotentialFile: d:/dev/istock-data/huaPotential.txt
mcstFile: d:/dev/istock-data/mcst.txt
bavFile: d:/dev/istock-data/bav.txt
lpbFile: d:/dev/istock-data/lpb.txt
lpb2File: d:/dev/istock-data/lpb2.txt
hlb2File: d:/dev/istock-data/hlb2.txt
txtFile: d:/dev/istock-data/ids.txt
drumFile: d:/dev/istock-data/drum.txt
drumsPath: d:/dev/istock-data/drums
b21File: d:/dev/istock-data/b21.txt
quarterCompareFile: d:/dev/istock-data/quarterCompare.txt
makersFile: d:/dev/istock-data/makers.txt
indexFile: d:/dev/istock-data/kdata/tushare/index/index.txt
fundsFile: d:/dev/istock-data/funds.txt
fundsPath: D:/dev/istock-data/funds
tushareUrl: http://api.waditu.com
dimensionsFile: D:/dev/istock-data/dimensions.txt
operationsFile: D:/dev/istock-data/operations.txt
openDuration: 89
dropDuration: 21



