sinaKdataPath: D:/prod/istock/data/kdata/sina
dzhKdataPath: D:/dev/istock/data/kdata/dzh
tushareKdataPath: D:/dev/istock/data/kdata/tushare
tushareItemsFile: D:/dev/istock/data/tushare_items.json
holdsFile: D:/dev/istock/data/holds.txt
preysFile: D:/dev/istock/data/preys.csv
favorsFile: D:/dev/istock/data/favors.txt



