fdataPath: D:/dev/istock-data/fdata/
sinaKdataPath: D:/dev/istock-data/kdata/sina
dzhKdataPath: D:/dev/istock-data/kdata/dzh
tushareKdataPath: D:/dev/istock-data/kdata/tushare
kdataPath163: D:/dev/istock-data/kdata/163
reportPath: D:/dev/istock-data/reports
musterPath: d:/dev/istock-data/kdata/muster
tmpMusterPath: d:/dev/istock-data/kdata/muster_tmp
tushareItemsFile: D:/dev/istock-data/tushare_items.json
holdsFile: D:/dev/istock-data/holds.txt
favorsFile: D:/dev/istock-data/favors.txt
bluechipsFile: D:/dev/istock-data/bluechips.json
topicsFile: D:/dev/istock-data/topics.txt
fvaluesOfHLFile: D:/dev/istock-data/fvaluesOfHL.txt
dailyMeansFile: D:/dev/istock-data/dailyMeans.txt
openDuration: 89
dropDuration: 34



