fdataPath: D:/dev/istock-data/fdata/
sinaKdataPath: D:/dev/istock-data/kdata/sina
dzhKdataPath: D:/dev/istock-data/kdata/dzh
tushareKdataPath: D:/dev/istock-data/kdata/tushare
kdataPath163: D:/dev/istock-data/kdata/163
reportPath: D:/dev/istock-data/reports
tushareItemsFile: D:/dev/istock-data/tushare_items.json
holdsFile: D:/dev/istock-data/holds.txt
preysFile: D:/dev/istock-data/preys.csv
favorsFile: D:/dev/istock-data/favors.txt
dailyAmountTopsFile: D:/dev/istock-data/dailyAmountTops.txt
latestAverageAmountTopsFile: D:/dev/istock-data/latestAverageAmountTops.txt
averageAmountTopsFile: D:/dev/istock-data/averageAmountTops.txt
bluechipsFile: D:/dev/istock-data/bluechips.json
latestHighLowTopsFile: D:/dev/istock-data/latestHighLowTops.txt
highLowTopsFile: D:/dev/istock-data/highLowTops.txt
twinOpenListFile: D:/dev/istock-data/twinOpenList.txt
twinDropListFile: D:/dev/istock-data/twinDropList.txt
amountGapsFile: D:/dev/istock-data/amountGaps.txt
latestPotentialsFile: D:/dev/istock-data/latestPotentials.txt
tmpLatestPotentialsFile: D:/dev/istock-data/tmpLatestPotentials.txt
breakersFile: D:/dev/istock-data/breakers.txt
breakersSortByHLFile: D:/dev/istock-data/breakersSortByHL.txt
breakersSortByDTFile: D:/dev/istock-data/breakersSortByDT.txt
breakersSortByAVFile: D:/dev/istock-data/breakersSortByAV.txt
fvaluesOfHLFile: D:/dev/istock-data/fvaluesOfHL.txt
topicsFile: D:/dev/istock-data/topics.txt




