fdataPath: D:/dev/istock-data/fdata/
sinaKdataPath: D:/dev/istock-data/kdata/sina
dzhKdataPath: D:/dev/istock-data/kdata/dzh
tushareKdataPath: D:/dev/istock-data/kdata/tushare
kdataPath163: D:/dev/istock-data/kdata/163
reportPath: D:/dev/istock-data/reports
musterPath: d:/dev/istock-data/kdata/muster
tushareItemsFile: D:/dev/istock-data/tushare_items.json
holdsFile: D:/dev/istock-data/holds.txt
favorsFile: D:/dev/istock-data/favors.txt
dailyAmountTopsFile: D:/dev/istock-data/dailyAmountTops.txt
averageAmountTopsFile: D:/dev/istock-data/averageAmountTops.txt
highLowTopsFile: D:/dev/istock-data/highLowTops.txt
bluechipsFile: D:/dev/istock-data/bluechips.json
latestPotentialsFile: D:/dev/istock-data/latestPotentials.txt
breakersFile: D:/dev/istock-data/breakers.txt
breakersSortByHLFile: D:/dev/istock-data/breakersSortByHL.txt
breakersSortByDTFile: D:/dev/istock-data/breakersSortByDT.txt
breakersSortByAVFile: D:/dev/istock-data/breakersSortByAV.txt
fvaluesOfHLFile: D:/dev/istock-data/fvaluesOfHL.txt
topicsFile: D:/dev/istock-data/topics.txt
kdataMusterFile: D:/dev/istock-data/kdata/kdataMuster.txt
latestFactorsFile: D:/dev/istock-data/kdata/tushare/latestFactors.txt



